version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

  nginx:
    build: ./nginx
    ports:
      - "8081:80"
    depends_on:
      - frontend
      - backend
